#!/usr/bin/env python3
"""Generates core/emojiData.js from Unicode's emoji-test.txt and the CLDR
English annotations (keywords). Not part of the extension; run it to update
the emoji list for a new Unicode version:

    curl -sSLo /tmp/emoji-test.txt https://unicode.org/Public/emoji/latest/emoji-test.txt
    curl -sSLo /tmp/en.xml https://raw.githubusercontent.com/unicode-org/cldr/main/common/annotations/en.xml
    tools/gen-emoji.py /tmp/emoji-test.txt /tmp/en.xml > core/emojiData.js

Skin-tone variants are left out (they would multiply the list by six); the
neutral emoji is listed once. Component-only entries (skin tones, hair) are
skipped too.
"""
import re
import sys
import xml.etree.ElementTree as ET

SKIN_TONES = {0x1F3FB, 0x1F3FC, 0x1F3FD, 0x1F3FE, 0x1F3FF}


def main(test_path, annotations_path):
    keywords = {}
    for node in ET.parse(annotations_path).getroot().iter("annotation"):
        if node.get("type") == "tts":
            continue
        keywords[node.get("cp")] = [k.strip() for k in node.text.split("|")]

    version = ""
    group = ""
    entries = []
    seen = set()
    with open(test_path, encoding="utf-8") as f:
        for line in f:
            if line.startswith("# Version:"):
                version = line.split(":", 1)[1].strip()
            if line.startswith("# group:"):
                group = line.split(":", 1)[1].strip()
                continue
            if not line.strip() or line.startswith("#"):
                continue
            if group == "Component":
                continue
            codes, rest = line.split(";", 1)
            status, comment = rest.split("#", 1)
            if status.strip() != "fully-qualified":
                continue
            cps = [int(c, 16) for c in codes.split()]
            if any(cp in SKIN_TONES for cp in cps):
                continue
            match = re.match(r"\s*(\S+)\s+E\d+\.\d+\s+(.*)", comment)
            emoji, name = match.group(1), match.group(2).strip()
            if emoji in seen:
                continue
            seen.add(emoji)
            words = []
            for k in keywords.get(emoji, []):
                k = k.lower()
                if k not in words and k not in name.lower():
                    words.append(k)
            entries.append((emoji, name, " ".join(words), group))

    print("// Generated by tools/gen-emoji.py from Unicode emoji-test.txt v%s and the" % version)
    print("// CLDR English annotations. © Unicode, Inc.; licensed under the Unicode")
    print("// License v3 (https://www.unicode.org/license.txt). Do not edit by hand.")
    print("//")
    print("// Each entry is \"emoji|name|keywords|group\"; see core/emoji.js.")
    print()
    print("export const EMOJI_DATA = [")
    for emoji, name, words, grp in entries:
        text = "|".join([emoji, name, words, grp]).replace("\\", "\\\\").replace("'", "\\'")
        print("    '%s'," % text)
    print("];")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2])
